# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
    nodejs: "24"
  jobs:
    install:
       # Since the install step is overridden, pip is no longer updated automatically.
       - pip install --upgrade pip
       - pip install .[mysql,knx,dmx,mqtt,pulse,telegram,file_persistence] --group doc
       - pip install "mido>=1.2.9,<2"

sphinx:
  configuration: docs/conf.py
